services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: ton_cle_api_openai
      - key: TWITCH_USER
        value: Gaufromatic
      - key: TWITCH_AUTH
        value: oauth:xxx_ton_token_depuis_twitchtokengenerator
      - key: TWITCH_CLIENT_ID
        value: ton_client_id_depuis_dev.twitch.tv
      - key: TWITCH_CLIENT_SECRET
        value: ton_client_secret_depuis_dev.twitch.tv
      - key: CHANNELS
        value: gaufregentille
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "false"
      - key: ENABLE_CHANNEL_POINTS
        value: "false"
      - key: PORT
        value: "3000"
